liquidinvestigations/cluster

- cluster.py
@gabriel-v 
I solved the issue that for -dev flag (fixes #5).
If we have an option in cluster.ini and is set like:
[cluster]
dev = True
-dev flag is set in supervisor config template.
> Adding -dev flag

- cluster.py
Please test the new versions on MacOS and Linux and confirm if they work (i.e. you can spin up a functional liquid node) in the comments.
> Bump Nomad and Consul versions

- Readme.md
- cluster.py
Sometimes you just want to run in foreground, without supervisor. I suspect this will be useful on MacOS.
> "runserver" command

- cluster.py
Added different variable for nomad advertise along side with nomad address for the vagrant updates.
> Vagrant update

- cluster.py
* Wait for Vault to start up
* Initialize Vault and save the secrets in `var/vault-secrets.ini`
* Use the secrets to unseal the vault
* Configure Nomad with the Vault root token
> `./cluster.py autovault`

- Readme.md
- cluster.py
- examples/cluster.ini
> Example config + readme update

- Readme.md
- examples/network.sh
Do we want to throw iptables in here?
Do we want to use the IP and bridge name set up here in `examples/config.ini` instead of the localhost ones?
> Example script to set up network

- cluster.py
Defaulting to `DEBUG` is too spammy.
> Set log level

- Readme.md
- examples/cluster.ini
Change some defaults to what we currently recommend.
> Setup steps

- Readme.md
- cluster.py
- examples/cluster.ini
- examples/docker.sh
> Multi host

- .drone.yml
https://cloud.docker.com/u/liquidinvestigations/repository/docker/liquidinvestigations/cluster has fresh tags now
> drone: publish to docker hub

- examples/docker.sh
Run as `./examples/docker.sh --rm` to remove the old container and create a new one. So, a one-liner to upgrade the cluster would be:
```shell
docker pull liquidinvestigations/cluster && ./examples/docker.sh --rm
```
> Stop and remove the old docker container

- cluster.py
We're actually after a few bug fixes in v0.9.4.
See https://github.com/hashicorp/nomad/releases
> update nomad to v0.9.5

- Readme.md
- cluster.py
- templates/docker-system-prune.nomad
https://github.com/hashicorp/nomad/issues/1944
> Periodic system prune

- examples/cluster.ini
for https://github.com/liquidinvestigations/node/pull/189
> add meta flags for liquid CI to examples/cluster.ini

- .drone.yml
- ci/Vagrantfile
- ci/test-common.sh
- cluster.py
- templates/cluster-fabio.nomad
Seems to have drifted into the red
> Fix the ci

- scripts/forward-ports.sh
Sometimes you want to run a DNS service, and guess what, DNS works over UDP :)
> Forward both TCP and UDP

- docker-entrypoint.sh
Maybe `/dev/kvm` does not exist
> Optional kvm

- Dockerfile
Install netcat and socat, vmck uses both.
> Netcat, socat

- cluster.py
https://github.com/hashicorp/nomad/releases/tag/v0.10.0
> update nomad version to 0.10

- cluster.py
- examples/cluster.ini
- templates/influxdb.nomad
- templates/prometheus.nomad
> configurable memory limits for influxdb and prom

- templates/prometheus.nomad
closes https://github.com/liquidinvestigations/cluster/issues/94
> Mount prometheus data dir

- cluster.py
v0.9.5 that we know and love. Not even v0.9.6 for all the bugs it may fix.
> Revert to the previous nomad experience

- Readme.md
How to run a known version of `cluster`
> Run a tagged version of cluster

- cluster.py
They've been working on demo for the past week.
> get new versions for nomad, consul, vault

- .drone.yml
- cluster.py
This updates the versions for nomad, vault, consul, vmck/vmck and its vagrant plugin.
> Update nomad 0.11.1

- docs/Docker-Installation.md
Change the documentation to prevent users running the cluster as root
> Change documentation for nonroot

- Readme.md
> firewall hint and link to node setup
